dist: trusty
sudo: required
cache: pip
language: python
matrix:  
    - os: linux
      python: "3.7"
  fast_finish: true
before_install:
  - if [[ -n "$TRAVIS_TAG" && "$TRAVIS_PYTHON_VERSION" != "3.7" ]]; then travis_terminate 0; fi; # Deploy on 3.7
install:
  - pip install -U pip
  - pip install   
  - pip install ./kit/
  - pip freeze
before_script:
  - if [[ "$TRAVIS_PYTHON_VERSION" == "3.7" ]]; then black ./kit/ --line-length 120 --check; fi
# script:
#   - pytest
# after_success:
#   - coverage report
#   - codecov
deploy:
  provider: pypi
  user: microsoftkusto
  skip_upload_docs: true
  # password: use $PYPI_PASSWORD
  distributions: "travis_deploy" # Manual step
  on:
    tags: true
    python: '3.7'
    branch: master
